spring:
  jpa:
    database: MYSQL
  datasource:
      plataform: mysql
      url: jdbc:mysql://localhost:3306/trial
      username: root
      password: admin
      driverClassName: com.mysql.jdbc.Driver